%% TODO:
%% - Add links from Model 3 back to Model 1 and Model 2 (rewards)
%% - Make this prettier (i.e. bold model names)
%% - Add illustrations for each model
graph TD
	A[Input Sentence]
	B([Model 1: Extraction<br/><i>Text to Structured Answer</i>])
	C["Structured Answer<br/><i>&lt;Cause, Relation, Effect&gt;</i>"]
	D([Model 2: Reconstruction<br/><i>Output Sentence</i>])
	E[Reconstructed<br/><i>Natural Language Sentence</i>]
	F([Model 3<br/>Entailment])
	G[\Contradiction\]
	H[\Entailment\]
	I[\Neutral\]

	A --> B
	B --> C
	C --> D
	A --> F
	E --> F
	D --> E
	F --> G
	F --> H
	F --> I
