model_name: microsoft/deberta-v3-xsmall
train_data_path: ../data/entailment_tag/train.class.json
eval_data_path: ../data/entailment_tag/dev.class.json
learning_rate: 1e-05
num_epochs: 100
max_seq_length: 400
batch_size: 24
early_stopping_patience: 10
max_samples: null
output_path: output/classifier
seed: 0
output_name: fcr-entailment-v3-xsmall-combined
prompt: COMBINED
do_train: true
do_test: true
do_inference: true
do_evaluation: true
test_data_path: ../data/entailment_tag/test.class.json
infer_data_path: ../data/entailment_tag/train.class.json
dropout: null
lr_scheduler: constant
model_type: entailment
